# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import phxkv_pb2 as phxkv__pb2


class PhxKVStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/phxkv.PhxKV/Put',
                request_serializer=phxkv__pb2.PhxKVRequest.SerializeToString,
                response_deserializer=phxkv__pb2.PhxKVResponse.FromString,
                )
        self.GetLocal = channel.unary_unary(
                '/phxkv.PhxKV/GetLocal',
                request_serializer=phxkv__pb2.PhxKVRequest.SerializeToString,
                response_deserializer=phxkv__pb2.PhxKVResponse.FromString,
                )
        self.GetGlobal = channel.unary_unary(
                '/phxkv.PhxKV/GetGlobal',
                request_serializer=phxkv__pb2.PhxKVRequest.SerializeToString,
                response_deserializer=phxkv__pb2.PhxKVResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/phxkv.PhxKV/Delete',
                request_serializer=phxkv__pb2.PhxKVRequest.SerializeToString,
                response_deserializer=phxkv__pb2.PhxKVResponse.FromString,
                )


class PhxKVServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhxKVServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=phxkv__pb2.PhxKVRequest.FromString,
                    response_serializer=phxkv__pb2.PhxKVResponse.SerializeToString,
            ),
            'GetLocal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocal,
                    request_deserializer=phxkv__pb2.PhxKVRequest.FromString,
                    response_serializer=phxkv__pb2.PhxKVResponse.SerializeToString,
            ),
            'GetGlobal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobal,
                    request_deserializer=phxkv__pb2.PhxKVRequest.FromString,
                    response_serializer=phxkv__pb2.PhxKVResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=phxkv__pb2.PhxKVRequest.FromString,
                    response_serializer=phxkv__pb2.PhxKVResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phxkv.PhxKV', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhxKV(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/phxkv.PhxKV/Put',
            phxkv__pb2.PhxKVRequest.SerializeToString,
            phxkv__pb2.PhxKVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/phxkv.PhxKV/GetLocal',
            phxkv__pb2.PhxKVRequest.SerializeToString,
            phxkv__pb2.PhxKVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGlobal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/phxkv.PhxKV/GetGlobal',
            phxkv__pb2.PhxKVRequest.SerializeToString,
            phxkv__pb2.PhxKVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/phxkv.PhxKV/Delete',
            phxkv__pb2.PhxKVRequest.SerializeToString,
            phxkv__pb2.PhxKVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
